import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../auth/auth_providers.dart';
import 'app_shell.dart';
import '../auth/login_page.dart';
import '../profile/profile_page.dart';

GoRouter createRouter() {
  final auth = AuthGuard();
  return GoRouter(
    refreshListenable: auth,
    redirect: auth.redirect,
    routes: [
      GoRoute(path: '/login', builder: (ctx, st) => const LoginPage()),
      ShellRoute(
        builder: (ctx, st, child) => AdminShell(child: child),
        routes: [
          GoRoute(path: '/dashboard', builder: (ctx, st) => const _Dashboard()),
          GoRoute(path: '/profile', builder: (ctx, st) => const ProfilePage()),
          ...generatedFeatureRoutes(), // generated by CLI
        ],
      ),
    ],
  );
}

class _Dashboard extends StatelessWidget {
  const _Dashboard();
  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('Welcome to OneFoodDialer Admin'));
  }
}

/// Placeholder for CLI-generated feature routes.
/// This will be replaced by the code generator with actual microservice routes.
List<RouteBase> generatedFeatureRoutes() {
  return [];
}

// Lightweight auth guard that listens to auth state via inherited change notifier.
class AuthGuard extends ChangeNotifier {
  bool _loggedIn = false;
  AuthGuard() {
    // TODO: wire to your riverpod auth state and call notifyListeners() on changes.
  }
  String? redirect(BuildContext context, GoRouterState state) {
    final loggingIn = state.matchedLocation == '/login';
    if (!_loggedIn && !loggingIn) return '/login';
    if (_loggedIn && loggingIn) return '/dashboard';
    return null;
  }
}
